### ISSUE TITLE
Support custom additional description as input from the workflow

### ISSUE THREAD

**Issue by nunesmatheus** [nunesmatheus/ai-codereviewer#5]
Users should be able to set some custom text, specific to their project/culture/guidelines so the comments generated by GPT are more relevant and useful.

The new field could be named `additional_prompt`, for example, to make it clear that it adds to the action default prompt, so people don't waste time building a basic prompt thinking that it will completely replace the prompt.

``` yaml
- name: Code Review
  uses: nunesmatheus/ai-codereviewer@main
  with:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    OPENAI_API_MODEL: "gpt-4o"
    exclude: "yarn.lock,dist/**"
    additional_prompt: "When applicable, mention a SOLID principle and how applying it would make the code easier to maintain, but don't spend more than 200 words explaining it."
```
