### ISSUE TITLE
Support setting the language for the pull request comments

### ISSUE THREAD

**Issue by nunesmatheus** [nunesmatheus/ai-codereviewer#6]
Users should be able to choose the language the comments from the pull request review should be made on, which can hopefully be achieved by setting this as an instruction on the prompt sent to the OpenAI API.

The new input could be named "language".

Example usage:

``` yaml
- name: Code Review
  uses: nunesmatheus/ai-codereviewer@main
  with:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    OPENAI_API_MODEL: "gpt-4o"
    exclude: "yarn.lock,dist/**"
    language: "Brazilian Portuguese"
```

I wonder if it could be problematic to allow open text there, but right now it looks like a very quick and effective solution for most cases.
